name: navigation_bar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_datetime_picker: ^1.5.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  intl: ^0.18.1

flutter:
  uses-material-design: true
